// packages/svelte-ui/src/components/progress/progress.svelte
<script lang="ts" module>
  import type { Progress as ProgressType } from "bits-ui";
  export type ProgressProps = ProgressType.RootProps & { class?: string };
</script>

<script lang="ts">
  import { Progress } from "bits-ui";
  import { cn } from "../../lib/utils";

  let { class: className, value, ...rest }: ProgressProps = $props();
</script>

<Progress.Root
  {value}
  class={cn(
    "relative h-4 w-full overflow-hidden rounded-full bg-secondary",
    className
  )}
  {...rest}
>
  <div
    class="h-full w-full flex-1 bg-primary transition-all"
    style="transform: translateX(-{100 - (value || 0)}%)"
  ></div>
</Progress.Root>

// packages/react-ui/src/components/progress.tsx
"use client";

import * as React from "react";
import * as ProgressPrimitive from "@radix-ui/react-progress";

import { cn } from "../lib/utils";

const Progress = React.forwardRef<
  React.ComponentRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn(
      "relative h-4 w-full overflow-hidden rounded-full bg-secondary",
      className
    )}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className="h-full w-full flex-1 bg-primary transition-all"
      style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
    />
  </ProgressPrimitive.Root>
));
Progress.displayName = ProgressPrimitive.Root.displayName;

export { Progress };
