// packages/svelte-ui/src/components/toggle-group/toggle-group.svelte
<script lang="ts" module>
  import type { ToggleGroup as ToggleGroupType } from "bits-ui";
  import type { ToggleVariant, ToggleSize } from "../toggle/index";

  export type ToggleGroupProps = ToggleGroupType.RootProps & {
    class?: string;
    variant?: ToggleVariant;
    size?: ToggleSize;
  };
</script>

<script lang="ts">
  import { ToggleGroup } from "bits-ui";
  import { cn } from "../../lib/utils";
  import { setContext } from "svelte";

  let {
    variant = "default",
    size = "default",
    class: className,
    children,
    ...rest
  }: ToggleGroupProps = $props();

  setContext("toggleGroup", { get variant() { return variant; }, get size() { return size; } });
</script>

<ToggleGroup.Root
  class={cn("flex items-center justify-center gap-1", className)}
  {...rest}
>
  {#if children}{@render children()}{/if}
</ToggleGroup.Root>

// packages/react-ui/src/components/toggle-group.tsx
"use client";

import * as React from "react";
import * as ToggleGroupPrimitive from "@radix-ui/react-toggle-group";
import { type VariantProps } from "class-variance-authority";

import { cn } from "../lib/utils";
import { toggleVariants } from "./toggle";

const ToggleGroupContext = React.createContext<
  VariantProps<typeof toggleVariants>
>({
  size: "default",
  variant: "default",
});

const ToggleGroup = React.forwardRef<
  React.ComponentRef<typeof ToggleGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ToggleGroupPrimitive.Root> &
    VariantProps<typeof toggleVariants>
>(({ className, variant, size, children, ...props }, ref) => (
  <ToggleGroupPrimitive.Root
    ref={ref}
    className={cn("flex items-center justify-center gap-1", className)}
    {...props}
  >
    <ToggleGroupContext.Provider value={{ variant, size }}>
      {children}
    </ToggleGroupContext.Provider>
  </ToggleGroupPrimitive.Root>
));

ToggleGroup.displayName = ToggleGroupPrimitive.Root.displayName;

const ToggleGroupItem = React.forwardRef<
  React.ComponentRef<typeof ToggleGroupPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof ToggleGroupPrimitive.Item> &
    VariantProps<typeof toggleVariants>
>(({ className, children, variant, size, ...props }, ref) => {
  const context = React.useContext(ToggleGroupContext);

  return (
    <ToggleGroupPrimitive.Item
      ref={ref}
      className={cn(
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        className
      )}
      {...props}
    >
      {children}
    </ToggleGroupPrimitive.Item>
  );
});

ToggleGroupItem.displayName = ToggleGroupPrimitive.Item.displayName;

export { ToggleGroup, ToggleGroupItem };
