// packages/react-ui/src/components/slider.tsx
"use client";

import * as React from "react";
import * as SliderPrimitive from "@radix-ui/react-slider";

import { cn } from "../lib/utils";

const Slider = React.forwardRef<
  React.ComponentRef<typeof SliderPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root>
>(({ className, ...props }, ref) => (
  <SliderPrimitive.Root
    ref={ref}
    className={cn(
      "relative flex w-full touch-none select-none items-center",
      className
    )}
    {...props}
  >
    <SliderPrimitive.Track className="relative h-2 w-full grow overflow-hidden rounded-full bg-secondary">
      <SliderPrimitive.Range className="absolute h-full bg-primary" />
    </SliderPrimitive.Track>
    <SliderPrimitive.Thumb className="block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50" />
  </SliderPrimitive.Root>
));
Slider.displayName = SliderPrimitive.Root.displayName;

export { Slider };

// packages/svelte-ui/src/components/slider/slider.svelte
<script lang="ts" module>
  import type { Slider as SliderType } from "bits-ui";
  export type SliderProps = SliderType.RootProps & { class?: string };
</script>

<script lang="ts">
  import { Slider } from "bits-ui";
  import { cn } from "../../lib/utils";

  let { class: className, ...rest }: SliderProps = $props();
</script>

<Slider.Root
  class={cn(
    "relative flex w-full touch-none select-none items-center",
    className
  )}
  {...rest}
>
  {#snippet children({ thumbs })}
    <Slider.Range class="absolute h-full bg-primary" />
    {#each thumbs as _, i}
      <Slider.Thumb
        index={i}
        class="block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
      />
    {/each}
  {/snippet}
</Slider.Root>
